export const AUTH_SUCCESS = 'AUTH_SUCCESS'
export const AUTH_LOGOUT = 'AUTH_LOGOUT'

export const CREATE_USER_EVENT = 'CREATE_USER_EVENT'


export const FETCH_EVENTLIST_START = 'FETCH_EVENTLIST_START'
export const FETCH_EVENTLIST_SUCCESS = 'FETCH_EVENTLIST_SUCCESS'
export const FETCH_EVENTLIST_ERROR = 'FETCH_EVENTLIST_ERROR'

export const DELETE_EVENT_SUCCESS = 'DELETE_EVENT_SUCCESS'
export const DELETE_EVENT_START = 'DELETE_EVENT_START'
export const DELETE_EVENT_ERROR = 'DELETE_EVENT_ERROR'


export const SET_INITIALIZED = 'SET_INITIALIZED'
export const INITIALIZED_SUCCESS = 'INITIALIZED_SUCCESS'